### ISSUE TITLE
pass context to mongodb connection initializer

### ISSUE THREAD

**Issue by kuami6** [NorskHelsenett/ror#73]
when initializing the mongodb connection we should be able to pass inn a context.
As of now the initializer code only sets a context.background. 
This would be nice to have so we can pass along traceids and such.

**Comment by havardelnan** [comment]
Whats the usecase where the connection is established in a context providing a traceid? The connection should be long lived and not a part of a "session" context. Querying the connection on the other hand allready requires a context as its part of the "session".

**Comment by kuami6** [comment]
That makes sense,  but shouldn't the connection at least share the context of the main process, created in main on program startup? I tried to dig around in the mongo-client to see what it actually uses the context for when connecting, but i got lost :)

**Comment by havardelnan** [comment]
@kuami6 got lost, closing issue
